databases:
  - name: replytsurai
    databaseName: replytsurai
    user: replytsurai

services:
  - type: web
    name: replytsurai
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: replytsurai
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false